//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWithEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string Year { get; set; }
        public Nullable<int> Pages { get; set; }
        public string Isbn { get; set; }
        public string Code { get; set; }
        public bool IsTaken { get; set; }
        public string TakenAt { get; set; }
        public string ReturnAt { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual users users { get; set; }
    }
}
