//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virtual_librarian.BookService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="api/BookService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        private System.DateTime YearField;
        
        private int PagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        private bool IsTakenField;
        
        private int ReaderIdField;
        
        private System.DateTime TakenAtField;
        
        private System.DateTime ReturnAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Pages {
            get {
                return this.PagesField;
            }
            set {
                if ((this.PagesField.Equals(value) != true)) {
                    this.PagesField = value;
                    this.RaisePropertyChanged("Pages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Isbn {
            get {
                return this.IsbnField;
            }
            set {
                if ((object.ReferenceEquals(this.IsbnField, value) != true)) {
                    this.IsbnField = value;
                    this.RaisePropertyChanged("Isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool IsTaken {
            get {
                return this.IsTakenField;
            }
            set {
                if ((this.IsTakenField.Equals(value) != true)) {
                    this.IsTakenField = value;
                    this.RaisePropertyChanged("IsTaken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int ReaderId {
            get {
                return this.ReaderIdField;
            }
            set {
                if ((this.ReaderIdField.Equals(value) != true)) {
                    this.ReaderIdField = value;
                    this.RaisePropertyChanged("ReaderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime TakenAt {
            get {
                return this.TakenAtField;
            }
            set {
                if ((this.TakenAtField.Equals(value) != true)) {
                    this.TakenAtField = value;
                    this.RaisePropertyChanged("TakenAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime ReturnAt {
            get {
                return this.ReturnAtField;
            }
            set {
                if ((this.ReturnAtField.Equals(value) != true)) {
                    this.ReturnAtField = value;
                    this.RaisePropertyChanged("ReturnAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="api/BookService", ConfigurationName="BookService.BookServiceSoap")]
    public interface BookServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace api/BookService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/HelloWorld", ReplyAction="*")]
        Virtual_librarian.BookService.HelloWorldResponse HelloWorld(Virtual_librarian.BookService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.HelloWorldResponse> HelloWorldAsync(Virtual_librarian.BookService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetBookByIdResult from namespace api/BookService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetBookById", ReplyAction="*")]
        Virtual_librarian.BookService.GetBookByIdResponse GetBookById(Virtual_librarian.BookService.GetBookByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetBookById", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.GetBookByIdResponse> GetBookByIdAsync(Virtual_librarian.BookService.GetBookByIdRequest request);
        
        // CODEGEN: Generating message contract since element name isbn from namespace api/BookService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetBookByCode", ReplyAction="*")]
        Virtual_librarian.BookService.GetBookByCodeResponse GetBookByCode(Virtual_librarian.BookService.GetBookByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetBookByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.GetBookByCodeResponse> GetBookByCodeAsync(Virtual_librarian.BookService.GetBookByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name isbn from namespace api/BookService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetBookByIsbn", ReplyAction="*")]
        Virtual_librarian.BookService.GetBookByIsbnResponse GetBookByIsbn(Virtual_librarian.BookService.GetBookByIsbnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetBookByIsbn", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.GetBookByIsbnResponse> GetBookByIsbnAsync(Virtual_librarian.BookService.GetBookByIsbnRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllBooksResult from namespace api/BookService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetAllBooks", ReplyAction="*")]
        Virtual_librarian.BookService.GetAllBooksResponse GetAllBooks(Virtual_librarian.BookService.GetAllBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetAllBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.GetAllBooksResponse> GetAllBooksAsync(Virtual_librarian.BookService.GetAllBooksRequest request);
        
        // CODEGEN: Generating message contract since element name GetReadersBooksResult from namespace api/BookService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetReadersBooks", ReplyAction="*")]
        Virtual_librarian.BookService.GetReadersBooksResponse GetReadersBooks(Virtual_librarian.BookService.GetReadersBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetReadersBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.GetReadersBooksResponse> GetReadersBooksAsync(Virtual_librarian.BookService.GetReadersBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/ReturnBook", ReplyAction="*")]
        bool ReturnBook(int returnedBookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/ReturnBook", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ReturnBookAsync(int returnedBookId);
        
        // CODEGEN: Generating message contract since element name search from namespace api/BookService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/Find", ReplyAction="*")]
        Virtual_librarian.BookService.FindResponse Find(Virtual_librarian.BookService.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.FindResponse> FindAsync(Virtual_librarian.BookService.FindRequest request);
        
        // CODEGEN: Generating message contract since element name newBook from namespace api/BookService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/EditBook", ReplyAction="*")]
        Virtual_librarian.BookService.EditBookResponse EditBook(Virtual_librarian.BookService.EditBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/EditBook", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.EditBookResponse> EditBookAsync(Virtual_librarian.BookService.EditBookRequest request);
        
        // CODEGEN: Generating message contract since element name book from namespace api/BookService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/DeleteBook", ReplyAction="*")]
        Virtual_librarian.BookService.DeleteBookResponse DeleteBook(Virtual_librarian.BookService.DeleteBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/DeleteBook", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.DeleteBookResponse> DeleteBookAsync(Virtual_librarian.BookService.DeleteBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/TakeBook", ReplyAction="*")]
        bool TakeBook(int takenBookId, int readerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/TakeBook", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> TakeBookAsync(int takenBookId, int readerId);
        
        // CODEGEN: Generating message contract since element name book from namespace api/BookService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/AddNewBook", ReplyAction="*")]
        Virtual_librarian.BookService.AddNewBookResponse AddNewBook(Virtual_librarian.BookService.AddNewBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/AddNewBook", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.AddNewBookResponse> AddNewBookAsync(Virtual_librarian.BookService.AddNewBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/RenewBook", ReplyAction="*")]
        bool RenewBook(int renewedBookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/RenewBook", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RenewBookAsync(int renewedBookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/IsBookAlreadyTaken", ReplyAction="*")]
        bool IsBookAlreadyTaken(int bookToCheckId);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/IsBookAlreadyTaken", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsBookAlreadyTakenAsync(int bookToCheckId);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetNextId", ReplyAction="*")]
        int GetNextId();
        
        [System.ServiceModel.OperationContractAttribute(Action="api/BookService/GetNextId", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetNextIdAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Virtual_librarian.BookService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Virtual_librarian.BookService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookById", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.GetBookByIdRequestBody Body;
        
        public GetBookByIdRequest() {
        }
        
        public GetBookByIdRequest(Virtual_librarian.BookService.GetBookByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class GetBookByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetBookByIdRequestBody() {
        }
        
        public GetBookByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByIdResponse", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.GetBookByIdResponseBody Body;
        
        public GetBookByIdResponse() {
        }
        
        public GetBookByIdResponse(Virtual_librarian.BookService.GetBookByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class GetBookByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Virtual_librarian.BookService.Book GetBookByIdResult;
        
        public GetBookByIdResponseBody() {
        }
        
        public GetBookByIdResponseBody(Virtual_librarian.BookService.Book GetBookByIdResult) {
            this.GetBookByIdResult = GetBookByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByCode", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.GetBookByCodeRequestBody Body;
        
        public GetBookByCodeRequest() {
        }
        
        public GetBookByCodeRequest(Virtual_librarian.BookService.GetBookByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class GetBookByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        public GetBookByCodeRequestBody() {
        }
        
        public GetBookByCodeRequestBody(string isbn, string code) {
            this.isbn = isbn;
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByCodeResponse", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.GetBookByCodeResponseBody Body;
        
        public GetBookByCodeResponse() {
        }
        
        public GetBookByCodeResponse(Virtual_librarian.BookService.GetBookByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class GetBookByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Virtual_librarian.BookService.Book GetBookByCodeResult;
        
        public GetBookByCodeResponseBody() {
        }
        
        public GetBookByCodeResponseBody(Virtual_librarian.BookService.Book GetBookByCodeResult) {
            this.GetBookByCodeResult = GetBookByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByIsbnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByIsbn", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.GetBookByIsbnRequestBody Body;
        
        public GetBookByIsbnRequest() {
        }
        
        public GetBookByIsbnRequest(Virtual_librarian.BookService.GetBookByIsbnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class GetBookByIsbnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isbn;
        
        public GetBookByIsbnRequestBody() {
        }
        
        public GetBookByIsbnRequestBody(string isbn) {
            this.isbn = isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByIsbnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByIsbnResponse", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.GetBookByIsbnResponseBody Body;
        
        public GetBookByIsbnResponse() {
        }
        
        public GetBookByIsbnResponse(Virtual_librarian.BookService.GetBookByIsbnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class GetBookByIsbnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Virtual_librarian.BookService.Book GetBookByIsbnResult;
        
        public GetBookByIsbnResponseBody() {
        }
        
        public GetBookByIsbnResponseBody(Virtual_librarian.BookService.Book GetBookByIsbnResult) {
            this.GetBookByIsbnResult = GetBookByIsbnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBooks", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.GetAllBooksRequestBody Body;
        
        public GetAllBooksRequest() {
        }
        
        public GetAllBooksRequest(Virtual_librarian.BookService.GetAllBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllBooksRequestBody {
        
        public GetAllBooksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBooksResponse", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.GetAllBooksResponseBody Body;
        
        public GetAllBooksResponse() {
        }
        
        public GetAllBooksResponse(Virtual_librarian.BookService.GetAllBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class GetAllBooksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Virtual_librarian.BookService.Book> GetAllBooksResult;
        
        public GetAllBooksResponseBody() {
        }
        
        public GetAllBooksResponseBody(System.Collections.Generic.List<Virtual_librarian.BookService.Book> GetAllBooksResult) {
            this.GetAllBooksResult = GetAllBooksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReadersBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReadersBooks", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.GetReadersBooksRequestBody Body;
        
        public GetReadersBooksRequest() {
        }
        
        public GetReadersBooksRequest(Virtual_librarian.BookService.GetReadersBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class GetReadersBooksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int readerId;
        
        public GetReadersBooksRequestBody() {
        }
        
        public GetReadersBooksRequestBody(int readerId) {
            this.readerId = readerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReadersBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReadersBooksResponse", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.GetReadersBooksResponseBody Body;
        
        public GetReadersBooksResponse() {
        }
        
        public GetReadersBooksResponse(Virtual_librarian.BookService.GetReadersBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class GetReadersBooksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Virtual_librarian.BookService.Book> GetReadersBooksResult;
        
        public GetReadersBooksResponseBody() {
        }
        
        public GetReadersBooksResponseBody(System.Collections.Generic.List<Virtual_librarian.BookService.Book> GetReadersBooksResult) {
            this.GetReadersBooksResult = GetReadersBooksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Find", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.FindRequestBody Body;
        
        public FindRequest() {
        }
        
        public FindRequest(Virtual_librarian.BookService.FindRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class FindRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string search;
        
        public FindRequestBody() {
        }
        
        public FindRequestBody(string search) {
            this.search = search;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindResponse", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.FindResponseBody Body;
        
        public FindResponse() {
        }
        
        public FindResponse(Virtual_librarian.BookService.FindResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class FindResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Virtual_librarian.BookService.Book> FindResult;
        
        public FindResponseBody() {
        }
        
        public FindResponseBody(System.Collections.Generic.List<Virtual_librarian.BookService.Book> FindResult) {
            this.FindResult = FindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditBook", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.EditBookRequestBody Body;
        
        public EditBookRequest() {
        }
        
        public EditBookRequest(Virtual_librarian.BookService.EditBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class EditBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int bookId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Virtual_librarian.BookService.Book newBook;
        
        public EditBookRequestBody() {
        }
        
        public EditBookRequestBody(int bookId, Virtual_librarian.BookService.Book newBook) {
            this.bookId = bookId;
            this.newBook = newBook;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditBookResponse", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.EditBookResponseBody Body;
        
        public EditBookResponse() {
        }
        
        public EditBookResponse(Virtual_librarian.BookService.EditBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class EditBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditBookResult;
        
        public EditBookResponseBody() {
        }
        
        public EditBookResponseBody(bool EditBookResult) {
            this.EditBookResult = EditBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBook", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.DeleteBookRequestBody Body;
        
        public DeleteBookRequest() {
        }
        
        public DeleteBookRequest(Virtual_librarian.BookService.DeleteBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class DeleteBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Virtual_librarian.BookService.Book book;
        
        public DeleteBookRequestBody() {
        }
        
        public DeleteBookRequestBody(Virtual_librarian.BookService.Book book) {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBookResponse", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.DeleteBookResponseBody Body;
        
        public DeleteBookResponse() {
        }
        
        public DeleteBookResponse(Virtual_librarian.BookService.DeleteBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class DeleteBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteBookResult;
        
        public DeleteBookResponseBody() {
        }
        
        public DeleteBookResponseBody(bool DeleteBookResult) {
            this.DeleteBookResult = DeleteBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewBook", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.AddNewBookRequestBody Body;
        
        public AddNewBookRequest() {
        }
        
        public AddNewBookRequest(Virtual_librarian.BookService.AddNewBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class AddNewBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Virtual_librarian.BookService.Book book;
        
        public AddNewBookRequestBody() {
        }
        
        public AddNewBookRequestBody(Virtual_librarian.BookService.Book book) {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewBookResponse", Namespace="api/BookService", Order=0)]
        public Virtual_librarian.BookService.AddNewBookResponseBody Body;
        
        public AddNewBookResponse() {
        }
        
        public AddNewBookResponse(Virtual_librarian.BookService.AddNewBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/BookService")]
    public partial class AddNewBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddNewBookResult;
        
        public AddNewBookResponseBody() {
        }
        
        public AddNewBookResponseBody(bool AddNewBookResult) {
            this.AddNewBookResult = AddNewBookResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookServiceSoapChannel : Virtual_librarian.BookService.BookServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceSoapClient : System.ServiceModel.ClientBase<Virtual_librarian.BookService.BookServiceSoap>, Virtual_librarian.BookService.BookServiceSoap {
        
        public BookServiceSoapClient() {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.BookService.HelloWorldResponse Virtual_librarian.BookService.BookServiceSoap.HelloWorld(Virtual_librarian.BookService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Virtual_librarian.BookService.HelloWorldRequest inValue = new Virtual_librarian.BookService.HelloWorldRequest();
            inValue.Body = new Virtual_librarian.BookService.HelloWorldRequestBody();
            Virtual_librarian.BookService.HelloWorldResponse retVal = ((Virtual_librarian.BookService.BookServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.HelloWorldResponse> Virtual_librarian.BookService.BookServiceSoap.HelloWorldAsync(Virtual_librarian.BookService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.BookService.HelloWorldResponse> HelloWorldAsync() {
            Virtual_librarian.BookService.HelloWorldRequest inValue = new Virtual_librarian.BookService.HelloWorldRequest();
            inValue.Body = new Virtual_librarian.BookService.HelloWorldRequestBody();
            return ((Virtual_librarian.BookService.BookServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.BookService.GetBookByIdResponse Virtual_librarian.BookService.BookServiceSoap.GetBookById(Virtual_librarian.BookService.GetBookByIdRequest request) {
            return base.Channel.GetBookById(request);
        }
        
        public Virtual_librarian.BookService.Book GetBookById(int id) {
            Virtual_librarian.BookService.GetBookByIdRequest inValue = new Virtual_librarian.BookService.GetBookByIdRequest();
            inValue.Body = new Virtual_librarian.BookService.GetBookByIdRequestBody();
            inValue.Body.id = id;
            Virtual_librarian.BookService.GetBookByIdResponse retVal = ((Virtual_librarian.BookService.BookServiceSoap)(this)).GetBookById(inValue);
            return retVal.Body.GetBookByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.GetBookByIdResponse> Virtual_librarian.BookService.BookServiceSoap.GetBookByIdAsync(Virtual_librarian.BookService.GetBookByIdRequest request) {
            return base.Channel.GetBookByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.BookService.GetBookByIdResponse> GetBookByIdAsync(int id) {
            Virtual_librarian.BookService.GetBookByIdRequest inValue = new Virtual_librarian.BookService.GetBookByIdRequest();
            inValue.Body = new Virtual_librarian.BookService.GetBookByIdRequestBody();
            inValue.Body.id = id;
            return ((Virtual_librarian.BookService.BookServiceSoap)(this)).GetBookByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.BookService.GetBookByCodeResponse Virtual_librarian.BookService.BookServiceSoap.GetBookByCode(Virtual_librarian.BookService.GetBookByCodeRequest request) {
            return base.Channel.GetBookByCode(request);
        }
        
        public Virtual_librarian.BookService.Book GetBookByCode(string isbn, string code) {
            Virtual_librarian.BookService.GetBookByCodeRequest inValue = new Virtual_librarian.BookService.GetBookByCodeRequest();
            inValue.Body = new Virtual_librarian.BookService.GetBookByCodeRequestBody();
            inValue.Body.isbn = isbn;
            inValue.Body.code = code;
            Virtual_librarian.BookService.GetBookByCodeResponse retVal = ((Virtual_librarian.BookService.BookServiceSoap)(this)).GetBookByCode(inValue);
            return retVal.Body.GetBookByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.GetBookByCodeResponse> Virtual_librarian.BookService.BookServiceSoap.GetBookByCodeAsync(Virtual_librarian.BookService.GetBookByCodeRequest request) {
            return base.Channel.GetBookByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.BookService.GetBookByCodeResponse> GetBookByCodeAsync(string isbn, string code) {
            Virtual_librarian.BookService.GetBookByCodeRequest inValue = new Virtual_librarian.BookService.GetBookByCodeRequest();
            inValue.Body = new Virtual_librarian.BookService.GetBookByCodeRequestBody();
            inValue.Body.isbn = isbn;
            inValue.Body.code = code;
            return ((Virtual_librarian.BookService.BookServiceSoap)(this)).GetBookByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.BookService.GetBookByIsbnResponse Virtual_librarian.BookService.BookServiceSoap.GetBookByIsbn(Virtual_librarian.BookService.GetBookByIsbnRequest request) {
            return base.Channel.GetBookByIsbn(request);
        }
        
        public Virtual_librarian.BookService.Book GetBookByIsbn(string isbn) {
            Virtual_librarian.BookService.GetBookByIsbnRequest inValue = new Virtual_librarian.BookService.GetBookByIsbnRequest();
            inValue.Body = new Virtual_librarian.BookService.GetBookByIsbnRequestBody();
            inValue.Body.isbn = isbn;
            Virtual_librarian.BookService.GetBookByIsbnResponse retVal = ((Virtual_librarian.BookService.BookServiceSoap)(this)).GetBookByIsbn(inValue);
            return retVal.Body.GetBookByIsbnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.GetBookByIsbnResponse> Virtual_librarian.BookService.BookServiceSoap.GetBookByIsbnAsync(Virtual_librarian.BookService.GetBookByIsbnRequest request) {
            return base.Channel.GetBookByIsbnAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.BookService.GetBookByIsbnResponse> GetBookByIsbnAsync(string isbn) {
            Virtual_librarian.BookService.GetBookByIsbnRequest inValue = new Virtual_librarian.BookService.GetBookByIsbnRequest();
            inValue.Body = new Virtual_librarian.BookService.GetBookByIsbnRequestBody();
            inValue.Body.isbn = isbn;
            return ((Virtual_librarian.BookService.BookServiceSoap)(this)).GetBookByIsbnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.BookService.GetAllBooksResponse Virtual_librarian.BookService.BookServiceSoap.GetAllBooks(Virtual_librarian.BookService.GetAllBooksRequest request) {
            return base.Channel.GetAllBooks(request);
        }
        
        public System.Collections.Generic.List<Virtual_librarian.BookService.Book> GetAllBooks() {
            Virtual_librarian.BookService.GetAllBooksRequest inValue = new Virtual_librarian.BookService.GetAllBooksRequest();
            inValue.Body = new Virtual_librarian.BookService.GetAllBooksRequestBody();
            Virtual_librarian.BookService.GetAllBooksResponse retVal = ((Virtual_librarian.BookService.BookServiceSoap)(this)).GetAllBooks(inValue);
            return retVal.Body.GetAllBooksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.GetAllBooksResponse> Virtual_librarian.BookService.BookServiceSoap.GetAllBooksAsync(Virtual_librarian.BookService.GetAllBooksRequest request) {
            return base.Channel.GetAllBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.BookService.GetAllBooksResponse> GetAllBooksAsync() {
            Virtual_librarian.BookService.GetAllBooksRequest inValue = new Virtual_librarian.BookService.GetAllBooksRequest();
            inValue.Body = new Virtual_librarian.BookService.GetAllBooksRequestBody();
            return ((Virtual_librarian.BookService.BookServiceSoap)(this)).GetAllBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.BookService.GetReadersBooksResponse Virtual_librarian.BookService.BookServiceSoap.GetReadersBooks(Virtual_librarian.BookService.GetReadersBooksRequest request) {
            return base.Channel.GetReadersBooks(request);
        }
        
        public System.Collections.Generic.List<Virtual_librarian.BookService.Book> GetReadersBooks(int readerId) {
            Virtual_librarian.BookService.GetReadersBooksRequest inValue = new Virtual_librarian.BookService.GetReadersBooksRequest();
            inValue.Body = new Virtual_librarian.BookService.GetReadersBooksRequestBody();
            inValue.Body.readerId = readerId;
            Virtual_librarian.BookService.GetReadersBooksResponse retVal = ((Virtual_librarian.BookService.BookServiceSoap)(this)).GetReadersBooks(inValue);
            return retVal.Body.GetReadersBooksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.GetReadersBooksResponse> Virtual_librarian.BookService.BookServiceSoap.GetReadersBooksAsync(Virtual_librarian.BookService.GetReadersBooksRequest request) {
            return base.Channel.GetReadersBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.BookService.GetReadersBooksResponse> GetReadersBooksAsync(int readerId) {
            Virtual_librarian.BookService.GetReadersBooksRequest inValue = new Virtual_librarian.BookService.GetReadersBooksRequest();
            inValue.Body = new Virtual_librarian.BookService.GetReadersBooksRequestBody();
            inValue.Body.readerId = readerId;
            return ((Virtual_librarian.BookService.BookServiceSoap)(this)).GetReadersBooksAsync(inValue);
        }
        
        public bool ReturnBook(int returnedBookId) {
            return base.Channel.ReturnBook(returnedBookId);
        }
        
        public System.Threading.Tasks.Task<bool> ReturnBookAsync(int returnedBookId) {
            return base.Channel.ReturnBookAsync(returnedBookId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.BookService.FindResponse Virtual_librarian.BookService.BookServiceSoap.Find(Virtual_librarian.BookService.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public System.Collections.Generic.List<Virtual_librarian.BookService.Book> Find(string search) {
            Virtual_librarian.BookService.FindRequest inValue = new Virtual_librarian.BookService.FindRequest();
            inValue.Body = new Virtual_librarian.BookService.FindRequestBody();
            inValue.Body.search = search;
            Virtual_librarian.BookService.FindResponse retVal = ((Virtual_librarian.BookService.BookServiceSoap)(this)).Find(inValue);
            return retVal.Body.FindResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.FindResponse> Virtual_librarian.BookService.BookServiceSoap.FindAsync(Virtual_librarian.BookService.FindRequest request) {
            return base.Channel.FindAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.BookService.FindResponse> FindAsync(string search) {
            Virtual_librarian.BookService.FindRequest inValue = new Virtual_librarian.BookService.FindRequest();
            inValue.Body = new Virtual_librarian.BookService.FindRequestBody();
            inValue.Body.search = search;
            return ((Virtual_librarian.BookService.BookServiceSoap)(this)).FindAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.BookService.EditBookResponse Virtual_librarian.BookService.BookServiceSoap.EditBook(Virtual_librarian.BookService.EditBookRequest request) {
            return base.Channel.EditBook(request);
        }
        
        public bool EditBook(int bookId, Virtual_librarian.BookService.Book newBook) {
            Virtual_librarian.BookService.EditBookRequest inValue = new Virtual_librarian.BookService.EditBookRequest();
            inValue.Body = new Virtual_librarian.BookService.EditBookRequestBody();
            inValue.Body.bookId = bookId;
            inValue.Body.newBook = newBook;
            Virtual_librarian.BookService.EditBookResponse retVal = ((Virtual_librarian.BookService.BookServiceSoap)(this)).EditBook(inValue);
            return retVal.Body.EditBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.EditBookResponse> Virtual_librarian.BookService.BookServiceSoap.EditBookAsync(Virtual_librarian.BookService.EditBookRequest request) {
            return base.Channel.EditBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.BookService.EditBookResponse> EditBookAsync(int bookId, Virtual_librarian.BookService.Book newBook) {
            Virtual_librarian.BookService.EditBookRequest inValue = new Virtual_librarian.BookService.EditBookRequest();
            inValue.Body = new Virtual_librarian.BookService.EditBookRequestBody();
            inValue.Body.bookId = bookId;
            inValue.Body.newBook = newBook;
            return ((Virtual_librarian.BookService.BookServiceSoap)(this)).EditBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.BookService.DeleteBookResponse Virtual_librarian.BookService.BookServiceSoap.DeleteBook(Virtual_librarian.BookService.DeleteBookRequest request) {
            return base.Channel.DeleteBook(request);
        }
        
        public bool DeleteBook(Virtual_librarian.BookService.Book book) {
            Virtual_librarian.BookService.DeleteBookRequest inValue = new Virtual_librarian.BookService.DeleteBookRequest();
            inValue.Body = new Virtual_librarian.BookService.DeleteBookRequestBody();
            inValue.Body.book = book;
            Virtual_librarian.BookService.DeleteBookResponse retVal = ((Virtual_librarian.BookService.BookServiceSoap)(this)).DeleteBook(inValue);
            return retVal.Body.DeleteBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.DeleteBookResponse> Virtual_librarian.BookService.BookServiceSoap.DeleteBookAsync(Virtual_librarian.BookService.DeleteBookRequest request) {
            return base.Channel.DeleteBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.BookService.DeleteBookResponse> DeleteBookAsync(Virtual_librarian.BookService.Book book) {
            Virtual_librarian.BookService.DeleteBookRequest inValue = new Virtual_librarian.BookService.DeleteBookRequest();
            inValue.Body = new Virtual_librarian.BookService.DeleteBookRequestBody();
            inValue.Body.book = book;
            return ((Virtual_librarian.BookService.BookServiceSoap)(this)).DeleteBookAsync(inValue);
        }
        
        public bool TakeBook(int takenBookId, int readerId) {
            return base.Channel.TakeBook(takenBookId, readerId);
        }
        
        public System.Threading.Tasks.Task<bool> TakeBookAsync(int takenBookId, int readerId) {
            return base.Channel.TakeBookAsync(takenBookId, readerId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.BookService.AddNewBookResponse Virtual_librarian.BookService.BookServiceSoap.AddNewBook(Virtual_librarian.BookService.AddNewBookRequest request) {
            return base.Channel.AddNewBook(request);
        }
        
        public bool AddNewBook(Virtual_librarian.BookService.Book book) {
            Virtual_librarian.BookService.AddNewBookRequest inValue = new Virtual_librarian.BookService.AddNewBookRequest();
            inValue.Body = new Virtual_librarian.BookService.AddNewBookRequestBody();
            inValue.Body.book = book;
            Virtual_librarian.BookService.AddNewBookResponse retVal = ((Virtual_librarian.BookService.BookServiceSoap)(this)).AddNewBook(inValue);
            return retVal.Body.AddNewBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.BookService.AddNewBookResponse> Virtual_librarian.BookService.BookServiceSoap.AddNewBookAsync(Virtual_librarian.BookService.AddNewBookRequest request) {
            return base.Channel.AddNewBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.BookService.AddNewBookResponse> AddNewBookAsync(Virtual_librarian.BookService.Book book) {
            Virtual_librarian.BookService.AddNewBookRequest inValue = new Virtual_librarian.BookService.AddNewBookRequest();
            inValue.Body = new Virtual_librarian.BookService.AddNewBookRequestBody();
            inValue.Body.book = book;
            return ((Virtual_librarian.BookService.BookServiceSoap)(this)).AddNewBookAsync(inValue);
        }
        
        public bool RenewBook(int renewedBookId) {
            return base.Channel.RenewBook(renewedBookId);
        }
        
        public System.Threading.Tasks.Task<bool> RenewBookAsync(int renewedBookId) {
            return base.Channel.RenewBookAsync(renewedBookId);
        }
        
        public bool IsBookAlreadyTaken(int bookToCheckId) {
            return base.Channel.IsBookAlreadyTaken(bookToCheckId);
        }
        
        public System.Threading.Tasks.Task<bool> IsBookAlreadyTakenAsync(int bookToCheckId) {
            return base.Channel.IsBookAlreadyTakenAsync(bookToCheckId);
        }
        
        public int GetNextId() {
            return base.Channel.GetNextId();
        }
        
        public System.Threading.Tasks.Task<int> GetNextIdAsync() {
            return base.Channel.GetNextIdAsync();
        }
    }
}
