//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virtual_librarian.PersonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="api/PersonService")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="api/PersonService", ConfigurationName="PersonService.PersonServiceSoap")]
    public interface PersonServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace api/PersonService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/HelloWorld", ReplyAction="*")]
        Virtual_librarian.PersonService.HelloWorldResponse HelloWorld(Virtual_librarian.PersonService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.HelloWorldResponse> HelloWorldAsync(Virtual_librarian.PersonService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace api/PersonService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/AddNewPerson", ReplyAction="*")]
        Virtual_librarian.PersonService.AddNewPersonResponse AddNewPerson(Virtual_librarian.PersonService.AddNewPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/AddNewPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.AddNewPersonResponse> AddNewPersonAsync(Virtual_librarian.PersonService.AddNewPersonRequest request);
        
        // CODEGEN: Generating message contract since element name person from namespace api/PersonService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/DeletePerson", ReplyAction="*")]
        Virtual_librarian.PersonService.DeletePersonResponse DeletePerson(Virtual_librarian.PersonService.DeletePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/DeletePerson", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.DeletePersonResponse> DeletePersonAsync(Virtual_librarian.PersonService.DeletePersonRequest request);
        
        // CODEGEN: Generating message contract since element name oldPerson from namespace api/PersonService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/EditPerson", ReplyAction="*")]
        Virtual_librarian.PersonService.EditPersonResponse EditPerson(Virtual_librarian.PersonService.EditPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/EditPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.EditPersonResponse> EditPersonAsync(Virtual_librarian.PersonService.EditPersonRequest request);
        
        // CODEGEN: Generating message contract since element name GetPersonByIDResult from namespace api/PersonService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/GetPersonByID", ReplyAction="*")]
        Virtual_librarian.PersonService.GetPersonByIDResponse GetPersonByID(Virtual_librarian.PersonService.GetPersonByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/GetPersonByID", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.GetPersonByIDResponse> GetPersonByIDAsync(Virtual_librarian.PersonService.GetPersonByIDRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace api/PersonService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/GetPersonByNameSurnamePassword", ReplyAction="*")]
        Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordResponse GetPersonByNameSurnamePassword(Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/GetPersonByNameSurnamePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordResponse> GetPersonByNameSurnamePasswordAsync(Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllPersonsResult from namespace api/PersonService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/GetAllPersons", ReplyAction="*")]
        Virtual_librarian.PersonService.GetAllPersonsResponse GetAllPersons(Virtual_librarian.PersonService.GetAllPersonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/GetAllPersons", ReplyAction="*")]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.GetAllPersonsResponse> GetAllPersonsAsync(Virtual_librarian.PersonService.GetAllPersonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/getNextId", ReplyAction="*")]
        int getNextId();
        
        [System.ServiceModel.OperationContractAttribute(Action="api/PersonService/getNextId", ReplyAction="*")]
        System.Threading.Tasks.Task<int> getNextIdAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Virtual_librarian.PersonService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Virtual_librarian.PersonService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewPerson", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.AddNewPersonRequestBody Body;
        
        public AddNewPersonRequest() {
        }
        
        public AddNewPersonRequest(Virtual_librarian.PersonService.AddNewPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class AddNewPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime birthDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string email;
        
        public AddNewPersonRequestBody() {
        }
        
        public AddNewPersonRequestBody(int id, string name, string surname, string password, System.DateTime birthDate, string phoneNumber, string email) {
            this.id = id;
            this.name = name;
            this.surname = surname;
            this.password = password;
            this.birthDate = birthDate;
            this.phoneNumber = phoneNumber;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewPersonResponse", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.AddNewPersonResponseBody Body;
        
        public AddNewPersonResponse() {
        }
        
        public AddNewPersonResponse(Virtual_librarian.PersonService.AddNewPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class AddNewPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddNewPersonResult;
        
        public AddNewPersonResponseBody() {
        }
        
        public AddNewPersonResponseBody(bool AddNewPersonResult) {
            this.AddNewPersonResult = AddNewPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePerson", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.DeletePersonRequestBody Body;
        
        public DeletePersonRequest() {
        }
        
        public DeletePersonRequest(Virtual_librarian.PersonService.DeletePersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class DeletePersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Virtual_librarian.PersonService.Person person;
        
        public DeletePersonRequestBody() {
        }
        
        public DeletePersonRequestBody(Virtual_librarian.PersonService.Person person) {
            this.person = person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePersonResponse", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.DeletePersonResponseBody Body;
        
        public DeletePersonResponse() {
        }
        
        public DeletePersonResponse(Virtual_librarian.PersonService.DeletePersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class DeletePersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeletePersonResult;
        
        public DeletePersonResponseBody() {
        }
        
        public DeletePersonResponseBody(bool DeletePersonResult) {
            this.DeletePersonResult = DeletePersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditPerson", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.EditPersonRequestBody Body;
        
        public EditPersonRequest() {
        }
        
        public EditPersonRequest(Virtual_librarian.PersonService.EditPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class EditPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Virtual_librarian.PersonService.Person oldPerson;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Virtual_librarian.PersonService.Person newPerson;
        
        public EditPersonRequestBody() {
        }
        
        public EditPersonRequestBody(Virtual_librarian.PersonService.Person oldPerson, Virtual_librarian.PersonService.Person newPerson) {
            this.oldPerson = oldPerson;
            this.newPerson = newPerson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditPersonResponse", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.EditPersonResponseBody Body;
        
        public EditPersonResponse() {
        }
        
        public EditPersonResponse(Virtual_librarian.PersonService.EditPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class EditPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditPersonResult;
        
        public EditPersonResponseBody() {
        }
        
        public EditPersonResponseBody(bool EditPersonResult) {
            this.EditPersonResult = EditPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonByID", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.GetPersonByIDRequestBody Body;
        
        public GetPersonByIDRequest() {
        }
        
        public GetPersonByIDRequest(Virtual_librarian.PersonService.GetPersonByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class GetPersonByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetPersonByIDRequestBody() {
        }
        
        public GetPersonByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonByIDResponse", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.GetPersonByIDResponseBody Body;
        
        public GetPersonByIDResponse() {
        }
        
        public GetPersonByIDResponse(Virtual_librarian.PersonService.GetPersonByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class GetPersonByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Virtual_librarian.PersonService.Person GetPersonByIDResult;
        
        public GetPersonByIDResponseBody() {
        }
        
        public GetPersonByIDResponseBody(Virtual_librarian.PersonService.Person GetPersonByIDResult) {
            this.GetPersonByIDResult = GetPersonByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonByNameSurnamePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonByNameSurnamePassword", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequestBody Body;
        
        public GetPersonByNameSurnamePasswordRequest() {
        }
        
        public GetPersonByNameSurnamePasswordRequest(Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class GetPersonByNameSurnamePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public GetPersonByNameSurnamePasswordRequestBody() {
        }
        
        public GetPersonByNameSurnamePasswordRequestBody(string name, string surname, string password) {
            this.name = name;
            this.surname = surname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonByNameSurnamePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonByNameSurnamePasswordResponse", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordResponseBody Body;
        
        public GetPersonByNameSurnamePasswordResponse() {
        }
        
        public GetPersonByNameSurnamePasswordResponse(Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class GetPersonByNameSurnamePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Virtual_librarian.PersonService.Person GetPersonByNameSurnamePasswordResult;
        
        public GetPersonByNameSurnamePasswordResponseBody() {
        }
        
        public GetPersonByNameSurnamePasswordResponseBody(Virtual_librarian.PersonService.Person GetPersonByNameSurnamePasswordResult) {
            this.GetPersonByNameSurnamePasswordResult = GetPersonByNameSurnamePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPersonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPersons", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.GetAllPersonsRequestBody Body;
        
        public GetAllPersonsRequest() {
        }
        
        public GetAllPersonsRequest(Virtual_librarian.PersonService.GetAllPersonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPersonsRequestBody {
        
        public GetAllPersonsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPersonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPersonsResponse", Namespace="api/PersonService", Order=0)]
        public Virtual_librarian.PersonService.GetAllPersonsResponseBody Body;
        
        public GetAllPersonsResponse() {
        }
        
        public GetAllPersonsResponse(Virtual_librarian.PersonService.GetAllPersonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="api/PersonService")]
    public partial class GetAllPersonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Virtual_librarian.PersonService.Person> GetAllPersonsResult;
        
        public GetAllPersonsResponseBody() {
        }
        
        public GetAllPersonsResponseBody(System.Collections.Generic.List<Virtual_librarian.PersonService.Person> GetAllPersonsResult) {
            this.GetAllPersonsResult = GetAllPersonsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonServiceSoapChannel : Virtual_librarian.PersonService.PersonServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonServiceSoapClient : System.ServiceModel.ClientBase<Virtual_librarian.PersonService.PersonServiceSoap>, Virtual_librarian.PersonService.PersonServiceSoap {
        
        public PersonServiceSoapClient() {
        }
        
        public PersonServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.PersonService.HelloWorldResponse Virtual_librarian.PersonService.PersonServiceSoap.HelloWorld(Virtual_librarian.PersonService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Virtual_librarian.PersonService.HelloWorldRequest inValue = new Virtual_librarian.PersonService.HelloWorldRequest();
            inValue.Body = new Virtual_librarian.PersonService.HelloWorldRequestBody();
            Virtual_librarian.PersonService.HelloWorldResponse retVal = ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.HelloWorldResponse> Virtual_librarian.PersonService.PersonServiceSoap.HelloWorldAsync(Virtual_librarian.PersonService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.PersonService.HelloWorldResponse> HelloWorldAsync() {
            Virtual_librarian.PersonService.HelloWorldRequest inValue = new Virtual_librarian.PersonService.HelloWorldRequest();
            inValue.Body = new Virtual_librarian.PersonService.HelloWorldRequestBody();
            return ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.PersonService.AddNewPersonResponse Virtual_librarian.PersonService.PersonServiceSoap.AddNewPerson(Virtual_librarian.PersonService.AddNewPersonRequest request) {
            return base.Channel.AddNewPerson(request);
        }
        
        public bool AddNewPerson(int id, string name, string surname, string password, System.DateTime birthDate, string phoneNumber, string email) {
            Virtual_librarian.PersonService.AddNewPersonRequest inValue = new Virtual_librarian.PersonService.AddNewPersonRequest();
            inValue.Body = new Virtual_librarian.PersonService.AddNewPersonRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.password = password;
            inValue.Body.birthDate = birthDate;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            Virtual_librarian.PersonService.AddNewPersonResponse retVal = ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).AddNewPerson(inValue);
            return retVal.Body.AddNewPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.AddNewPersonResponse> Virtual_librarian.PersonService.PersonServiceSoap.AddNewPersonAsync(Virtual_librarian.PersonService.AddNewPersonRequest request) {
            return base.Channel.AddNewPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.PersonService.AddNewPersonResponse> AddNewPersonAsync(int id, string name, string surname, string password, System.DateTime birthDate, string phoneNumber, string email) {
            Virtual_librarian.PersonService.AddNewPersonRequest inValue = new Virtual_librarian.PersonService.AddNewPersonRequest();
            inValue.Body = new Virtual_librarian.PersonService.AddNewPersonRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.password = password;
            inValue.Body.birthDate = birthDate;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            return ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).AddNewPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.PersonService.DeletePersonResponse Virtual_librarian.PersonService.PersonServiceSoap.DeletePerson(Virtual_librarian.PersonService.DeletePersonRequest request) {
            return base.Channel.DeletePerson(request);
        }
        
        public bool DeletePerson(Virtual_librarian.PersonService.Person person) {
            Virtual_librarian.PersonService.DeletePersonRequest inValue = new Virtual_librarian.PersonService.DeletePersonRequest();
            inValue.Body = new Virtual_librarian.PersonService.DeletePersonRequestBody();
            inValue.Body.person = person;
            Virtual_librarian.PersonService.DeletePersonResponse retVal = ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).DeletePerson(inValue);
            return retVal.Body.DeletePersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.DeletePersonResponse> Virtual_librarian.PersonService.PersonServiceSoap.DeletePersonAsync(Virtual_librarian.PersonService.DeletePersonRequest request) {
            return base.Channel.DeletePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.PersonService.DeletePersonResponse> DeletePersonAsync(Virtual_librarian.PersonService.Person person) {
            Virtual_librarian.PersonService.DeletePersonRequest inValue = new Virtual_librarian.PersonService.DeletePersonRequest();
            inValue.Body = new Virtual_librarian.PersonService.DeletePersonRequestBody();
            inValue.Body.person = person;
            return ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).DeletePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.PersonService.EditPersonResponse Virtual_librarian.PersonService.PersonServiceSoap.EditPerson(Virtual_librarian.PersonService.EditPersonRequest request) {
            return base.Channel.EditPerson(request);
        }
        
        public bool EditPerson(Virtual_librarian.PersonService.Person oldPerson, Virtual_librarian.PersonService.Person newPerson) {
            Virtual_librarian.PersonService.EditPersonRequest inValue = new Virtual_librarian.PersonService.EditPersonRequest();
            inValue.Body = new Virtual_librarian.PersonService.EditPersonRequestBody();
            inValue.Body.oldPerson = oldPerson;
            inValue.Body.newPerson = newPerson;
            Virtual_librarian.PersonService.EditPersonResponse retVal = ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).EditPerson(inValue);
            return retVal.Body.EditPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.EditPersonResponse> Virtual_librarian.PersonService.PersonServiceSoap.EditPersonAsync(Virtual_librarian.PersonService.EditPersonRequest request) {
            return base.Channel.EditPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.PersonService.EditPersonResponse> EditPersonAsync(Virtual_librarian.PersonService.Person oldPerson, Virtual_librarian.PersonService.Person newPerson) {
            Virtual_librarian.PersonService.EditPersonRequest inValue = new Virtual_librarian.PersonService.EditPersonRequest();
            inValue.Body = new Virtual_librarian.PersonService.EditPersonRequestBody();
            inValue.Body.oldPerson = oldPerson;
            inValue.Body.newPerson = newPerson;
            return ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).EditPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.PersonService.GetPersonByIDResponse Virtual_librarian.PersonService.PersonServiceSoap.GetPersonByID(Virtual_librarian.PersonService.GetPersonByIDRequest request) {
            return base.Channel.GetPersonByID(request);
        }
        
        public Virtual_librarian.PersonService.Person GetPersonByID(int id) {
            Virtual_librarian.PersonService.GetPersonByIDRequest inValue = new Virtual_librarian.PersonService.GetPersonByIDRequest();
            inValue.Body = new Virtual_librarian.PersonService.GetPersonByIDRequestBody();
            inValue.Body.id = id;
            Virtual_librarian.PersonService.GetPersonByIDResponse retVal = ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).GetPersonByID(inValue);
            return retVal.Body.GetPersonByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.GetPersonByIDResponse> Virtual_librarian.PersonService.PersonServiceSoap.GetPersonByIDAsync(Virtual_librarian.PersonService.GetPersonByIDRequest request) {
            return base.Channel.GetPersonByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.PersonService.GetPersonByIDResponse> GetPersonByIDAsync(int id) {
            Virtual_librarian.PersonService.GetPersonByIDRequest inValue = new Virtual_librarian.PersonService.GetPersonByIDRequest();
            inValue.Body = new Virtual_librarian.PersonService.GetPersonByIDRequestBody();
            inValue.Body.id = id;
            return ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).GetPersonByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordResponse Virtual_librarian.PersonService.PersonServiceSoap.GetPersonByNameSurnamePassword(Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequest request) {
            return base.Channel.GetPersonByNameSurnamePassword(request);
        }
        
        public Virtual_librarian.PersonService.Person GetPersonByNameSurnamePassword(string name, string surname, string password) {
            Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequest inValue = new Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequest();
            inValue.Body = new Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequestBody();
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.password = password;
            Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordResponse retVal = ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).GetPersonByNameSurnamePassword(inValue);
            return retVal.Body.GetPersonByNameSurnamePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordResponse> Virtual_librarian.PersonService.PersonServiceSoap.GetPersonByNameSurnamePasswordAsync(Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequest request) {
            return base.Channel.GetPersonByNameSurnamePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordResponse> GetPersonByNameSurnamePasswordAsync(string name, string surname, string password) {
            Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequest inValue = new Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequest();
            inValue.Body = new Virtual_librarian.PersonService.GetPersonByNameSurnamePasswordRequestBody();
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            inValue.Body.password = password;
            return ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).GetPersonByNameSurnamePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Virtual_librarian.PersonService.GetAllPersonsResponse Virtual_librarian.PersonService.PersonServiceSoap.GetAllPersons(Virtual_librarian.PersonService.GetAllPersonsRequest request) {
            return base.Channel.GetAllPersons(request);
        }
        
        public System.Collections.Generic.List<Virtual_librarian.PersonService.Person> GetAllPersons() {
            Virtual_librarian.PersonService.GetAllPersonsRequest inValue = new Virtual_librarian.PersonService.GetAllPersonsRequest();
            inValue.Body = new Virtual_librarian.PersonService.GetAllPersonsRequestBody();
            Virtual_librarian.PersonService.GetAllPersonsResponse retVal = ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).GetAllPersons(inValue);
            return retVal.Body.GetAllPersonsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Virtual_librarian.PersonService.GetAllPersonsResponse> Virtual_librarian.PersonService.PersonServiceSoap.GetAllPersonsAsync(Virtual_librarian.PersonService.GetAllPersonsRequest request) {
            return base.Channel.GetAllPersonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Virtual_librarian.PersonService.GetAllPersonsResponse> GetAllPersonsAsync() {
            Virtual_librarian.PersonService.GetAllPersonsRequest inValue = new Virtual_librarian.PersonService.GetAllPersonsRequest();
            inValue.Body = new Virtual_librarian.PersonService.GetAllPersonsRequestBody();
            return ((Virtual_librarian.PersonService.PersonServiceSoap)(this)).GetAllPersonsAsync(inValue);
        }
        
        public int getNextId() {
            return base.Channel.getNextId();
        }
        
        public System.Threading.Tasks.Task<int> getNextIdAsync() {
            return base.Channel.getNextIdAsync();
        }
    }
}
